name: Sync

on:
  # Monthly sync on the 1st of each month
  schedule:
    - cron: "0 0 1 * *"
  # Manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream (template) and merge
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git remote add upstream https://x-access-token:${TOKEN}@github.com/j-hc/revanced-magisk-module.git
          git fetch upstream main
          git checkout -b chore/template_sync_${{ github.run_id }}
          git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet origin/main; then
            echo "No changes to sync."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: "chore: sync with template repository"
          title: "chore: sync with template repository"
          body: |
            This PR syncs changes from the template repository (j-hc/revanced-magisk-module).

            ## Changes included:
            - Updates to build scripts and workflows
            - Configuration improvements
            - Documentation updates

            Please review these changes carefully before merging.
          branch: chore/template_sync_${{ github.run_id }}
          labels: sync,maintenance

      - name: Report sync status
        if: always()
        run: |
          if [ "${{ steps.diff.outputs.changed }}" == "true" ]; then
            echo "✅ Template sync completed and PR created"
          else
            echo "ℹ️ No changes detected during template sync"
          fi
